
services:
  - type: web
    name: Ãbùtïïëy Mahappen 
    env: node
    plan: free
    repo: https://happymahappen101-star.github.io/happymahappen.github.io/
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false  # Don't include the value here, will be entered manually on Render
      - key: OWNER_NUMBER
        sync: false
